project:
  type: website

website:
  sidebar:
    style: "floating"
    search: true
    pinned: false
    tools:
      - icon: twitter
        href: https://twitter.com/williamcorrearj
      - icon: github
        href: https://github.com/profwilliammelo
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - basics-knitr.qmd
          - basics-jupyter.qmd
      - section: "Layout"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
  twitter-card: true
  cookie-consent: true
  title: William Melo
  navbar:
    background: "#ffcccc"
    search: true
    left:
      - text: "Inicio"
        file: index.qmd
      - text: "Blog"
        file: orcamento.Rmd
# margin-header: |
#   ![Logo image](/images/logo.png)
# body-header: | 
#   This page brought to you by <https://example.com>
# margin-footer: |
#   ![FOOTER](/images/logo.png)
    
 

format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: true

editor: visual

